source = $HOME/.config/hypr/config/variables.conf
# Ignore maximize requests from apps
windowrule = match:class .*, suppress_event maximize
# Fix some dragging issues with XWayland
# windowrule = match:class ^$, match:title ^$, floating 1, fullscreen 0, pinned 0, no_focus
# No blur for empty class/title
windowrule = match:class ^()$, match:title ^()$, no_blur on
